stm32mp1: Fix board_get_alt_info_mtd()
Since MTD devices are partionned, we got the following
error when command "dfu 0" is executed:

DFU alt info setting: done
ERROR: Too many arguments for nor0
ERROR: DFU entities configuration failed!
ERROR: (partition table does not match dfu_alt_info?)

Signed-off-by: Patrice Chotard <patrice.chotard@foss.st.com>
Change-Id: I25ba0e5fd48d4f839a401cf6583fab54c25b61ab
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/u-boot/+/338195
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>
ACI: CIBUILD <MDG-smet-aci-builds@list.st.com>